app/routes.py
from flask import Blueprint, redirect, url_for, session, render_template, current_app, flash,get_flashed_messages,jsonify
from flask_login import login_user, logout_user, login_required, current_user
from app.models import User, Course
from app.forms import RegistrationForm, LoginForm, Enroll
from app.link_handler import get_src

main = Blueprint('main', __name__)

# Define the routes for the main blueprint
@main.route('/')
def index():
    return render_template('landing.html')


@main.route('/dash')
@login_required
def dashboard():
    name = current_user.name
    user_id = current_user.id
    user_email = current_user.email
    user_marks = User.get_user_marks(user_email)
    # print('this is the user marks', user_marks)
    # print('this is the user email', user_email)
    
    
    course_ids = User.get_user_courses(user_email)
    # print('this is the course ids', course_ids)
    courses = []    
    for course_id in course_ids:
        course = Course.get_course(course_id)
        course['src'] = get_src(course['embed_link'])
        courses.append(course)
    
    courses_marks = []
    if user_marks:
        for mark in user_marks:
            course = Course.get_course(mark['course_id'])
            courses_marks.append({'course': course, 'marks': mark['marks']})
            
    # print('this is courses marks', courses_marks)
    # print('this is course in courses marks', courses_marks[0]['course'])
    
        
        # print('in routes course', course['src'])

    # print(' this is the user email', user_email)
    # print('I should print courses here', courses)

    return render_template('student/dashboard.html', courses=courses, name=name, user_id=user_id, user_email=user_email, courses_marks=courses_marks)

@main.route('/chat')
@login_required
def chatbot():
    return render_template('student/chatbot.html')

@main.route('/learning')
@login_required
def learning():
    return render_template('student/learning.html')

@main.route('/test')
@login_required
def test():
    email = current_user.email
    name = current_user.name
    courses = User.get_user_courses(email) or []
    # course_dict = {}
    # course_dict[f'{name}\'s courses'] = courses or {}
    return render_template('student/test.html', courses=courses, name=name, email=email)

# TODO: Check why it is not validating  
@main.route('/courses', methods=['GET', 'POST'])
def courses(email=None, course_id=None):
    enroll = Enroll()
    if enroll.validate_on_submit():
        email = enroll.email.data
        User.add_course_to_user(email, course_id)
    # print("didnt validate the form") 
    courses = Course.get_all_courses()
    return render_template('student/courses.html', courses=courses, enroll=enroll)

@main.route('/liked_courses')
def liked_courses():
    return render_template('student/liked-course.html')

@main.route('/notification')
def notification():
    return render_template('student/notification.html')


@main.route('/auth', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data
        role = form.role.data
        existing_user = User.get_by_email(email)
        if existing_user is None:
            user = User.create(name, email, password, role)
            login_user(user)
            if role == 'student':
                return redirect(url_for('main.dashboard'))
            elif role == 'teacher':
                return redirect(url_for('main.dashboard_teacher'))
        else:
            flash('A user with that email already exists.')
    login_form = LoginForm()
    flash_messages = get_flashed_messages(with_categories=True)
    return render_template('auth.html', register_form=form, login_form=login_form, flash_messages=flash_messages)


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.get_by_email(form.email.data)
        if user and user.check_password(form.password.data):
            user_json = user.user_to_json()
            print('this is the user json', user_json)          
            login_user(user)
            if user_json['role'] == 'student':
                print('this is the user role', user.role )
                return redirect(url_for('main.dashboard'))
            elif user_json['role'] == 'teacher':
                print('this is the user role', user.role )
                return redirect(url_for('main.dashboard_teacher'))
            elif user_json['role'] == None:
                flash('Please Sign up')
            print('after all the checks')
        else:
            flash('Invalid email or password.')
    register_form = RegistrationForm()
    flash_messages = get_flashed_messages(with_categories=True)
    return render_template('auth.html', register_form=register_form, login_form=form, flash_messages=flash_messages)
    # return render_template('login.html', register_form=register_form, login_form=form)

# Google login
@main.route('/login-google')
def login_google():
    google = current_app.config['oauth_google']
    redirect_uri = url_for('main.authorize', _external=True)
    return google.authorize_redirect(redirect_uri)

@main.route('/auth/callback')
def authorize():
    google = current_app.config['oauth_google']
    token = google.authorize_access_token()
    userinfo = google.parse_id_token(token)
    user = User.get(userinfo['sub'])
    if not user:
        user = User.create(userinfo['sub'], userinfo['name'], userinfo['email'])
    session['user'] = {'id': userinfo['sub'], 'name': userinfo['name'], 'email': userinfo['email']}
    login_user(user)
    return redirect(url_for('main.dashboard'))

@main.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('user', None)
    return redirect(url_for('main.index'))

# teachers routes
####

#
######
#
#
#
#
#
#
#
#######

@main.route('/dashboard-teacher')
@login_required
def dashboard_teacher():
    all_students = User.get_all_users()
    my_courses = User.get_user_courses(current_user.email)

    course_names = []
    for course in my_courses:
        course = Course.get_course(course)
        course_names.append(course)
        
        
    my_students = []
    for student in all_students:
        if student['role'] == 'student':
            for course in student['courses']:
                if course in my_courses:
                    my_students.append(student)
                    break
    
    print('COURSE NAMES', course_names)

    return render_template('teacher/dashboard-teacher.html', my_students=my_students, course_names=course_names)


@main.route('/students')
def students():
    users = User.get_all_users()
    for user in users:
        if user['email'] == current_user.email:
            user_info = user
        user_courses = user_info['courses']
        courses = []
        for course in user_courses:
            course = Course.get_course(course)
            courses.append(course)
        print('this is the courses', courses)
    return render_template('teacher/students.html',user_courses=courses)

@main.route('/add-courses')
def add_courses():
    
    return render_template('teacher/upload-course.html')

@main.route('/send-notification')
def notify():
    return render_template('teacher/send-notification.html')


##
#
#
###
@main.route('/settings')
def settings():
    current_user = User.get(session['_user_id'])
    print('this is the current user', current_user)
    user_json = current_user.user_to_json()
    role = current_user.marks # the simple fix...
    return render_template('settings.html', role=role)

 

app/templates/teacher/base-teacher.html
<!DOCTYPE html>
<!-- Coding by CodingNepal | www.codingnepalweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Academi Franco Rwanda | Dashboard </title>
    <!-- Boxicons CDN Link -->

    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!----======== CSS ======== -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dash.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/add-courses.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/send-notification.css') }}">
    <!----===== Iconscout CSS ===== -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
<body>
  <div class="sidebar">
    <div class="logo-details">
      <i class="fas fa-copyright"></i>
      <span class="logo_name">Academie Franco</span>
    </div>
    <ul class="nav-links">
      <li>
        <a href="{{ url_for('main.dashboard_teacher')}}" class="nav-link" id="dashboard-tab">
          <i class='bx bx-grid-alt'></i>
          <span class="links_name">Dashboard</span>
        </a>
      </li>
      <li>
        <a href="{{ url_for('main.students') }}" class="nav-link" id="courses-tab">
          <i class='bx bx-box'></i>
          <span class="links_name">My Courses</span>
        </a>
      </li>
      <li>
        <a href="{{ url_for('main.add_courses') }}" class="nav-link" id="chatbot-tab">
          <i class='bx bx-list-ul'></i>
          <span class="links_name">New Course</span>
        </a>
      </li>
      <li>
        <a href="{{ url_for('main.notify') }}" class="nav-link" id="notification-tab">
          <i class='bx bx-pie-chart-alt-2'></i>
          <span class="links_name">Send Notification</span>
        </a>
      </li>
      <li>
        <a href="{{ url_for('main.settings') }}" class="nav-link" id="setting-tab">
          <i class='bx bx-cog'></i>
          <span class="links_name">Setting</span>
        </a>
      </li>
      <li class="log_out">
        <a href="{{url_for('main.logout') }}">
          <i class='bx bx-log-out'></i>
          <span class="links_name">Log out</span>
        </a>
      </li>
    </ul>
  </div>
  <section class="home-section">
    <nav>
      <div class="sidebar-button">
        <i class='bx bx-menu sidebarBtn'></i>
        <span class="dashboard">Dashboard</span>
      </div>
      <div class="search-box">
        <input type="text" placeholder="Search...">
        <i class='bx bx-search'></i>
      </div>
      <div class="profile-details">
        <span class="admin_name"><a href="">{{ current_user.name }}</a></span>
        <i class='bx bx-chevron-down'></i>
      </div>
    </nav>
    <div class="home-content">
      {% block content %}
      {% endblock %}
    </div>
  </section>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script>
    let sidebar = document.querySelector(".sidebar");
    let sidebarBtn = document.querySelector(".sidebarBtn");
    sidebarBtn.onclick = function() {
      sidebar.classList.toggle("active");
      if(sidebar.classList.contains("active")){
        sidebarBtn.classList.replace("bx-menu", "bx-menu-alt-right");
      } else {
        sidebarBtn.classList.replace("bx-menu-alt-right", "bx-menu");
      }
    }
  </script>
</body>
<script src="{{ url_for('static', filename='js/dashboard/courses.js') }}"></script>
</html>

app/templates/teacher/dashboard-teacher.html
{% extends "teacher/base-teacher.html" %}
{% block content %}
    <h1>Welcome, Teacher!</h1>
    <p>This is your dashboard where you can manage your classes, view student progress, and more.</p>
    {% if my_students %}
        <table class="table" style="width: 60%;">
            <div id="table">
                <thead>
                    <tr>
                        <th scope="col" style="width: 25%;">Student ID</th>
                        <th scope="col" style="width: 25%;">Student Full Name</th>
                        <th scope="col" style="width: 25%;">Course Taken</th>
                        <th scope="col" style="width: 25%;">Marks</th>
                    </tr>
                </thead>
                <tbody>
                    {% for my_student in my_students %}
                        <tr>
                            <th scope="row">{{ my_student._id }}</th>
                            <td>{{ my_student.name }}</td>
                            <td>
                                {% for course_name in course_names %}
                                    {% if course_name._id in my_student.courses %}
                                        {{ course_name.title }}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                {% for course_name in course_names %}
                                    {% if course_name._id in my_student.courses %}
                                        {{ course_name.marks }}
                                    {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </div>
        </table>
    {% else %}
        <p>You have no students yet.</p>
    {% endif %}
{% endblock %}

app/templates/teacher/send-notification.html
{% extends "teacher/base-teacher.html" %}
{% block content %}
<div class="container form-container">
    <h2 class="form-title text-center">Send Notification to Students</h2>
    <form id="blogForm">
        <div class="form-group">
            <label for="blog-title">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Title" required>
        </div>
        <div class="form-group">
            <label for="instructor-name">Instructor Name</label>
            <input type="text" class="form-control" id="instructor-name" name="instructor_name" placeholder="Enter your name" required>
        </div>
        <div class="form-group">
            <label for="description">Notification Description</label>
            <textarea class="form-control" id="description" name="description" rows="10" placeholder="Notes Description" required></textarea>
        </div>
        <button type="submit" class="btn btn-custom btn-block">Submit</button>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.getElementById('blogForm').addEventListener('submit', function(event) {
        event.preventDefault();

        // Gather form data
        const formData = new FormData(this);
        const data = {
            title: formData.get('title'),
            instructor_name: formData.get('instructor_name'),
            description: formData.get('description')
        };

        // Post data as JSON
        fetch("/api/v1/post_notification", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(data)
        })
        .then(response => response.json())
        .then(data => {
            Swal.fire({
                icon: 'success',
                title: 'Notification submitted successfully!',
                showConfirmButton: false,
                timer: 2000
            });
        })
        .catch(error => {
            console.error('Error:', error);
            Swal.fire({
                icon: 'error',
                title: 'Submission failed',
                text: 'Please try again later.',
                showConfirmButton: true
            });
        });
    });
</script>
{% endblock %}

app/templates/teacher/students.html
{% extends 'teacher/base-teacher.html' %}

{% block content %}
    <h1>Courses Dashboard</h1>
    <p>This is your dashboard where you can manage your classes, and more.</p>

    {% if user_courses %}

    <table class="table" style="width: 60%;">
        <thead>
          <tr>
            <th scope="col" style="width: 30%;">Course ID</th>
            <th scope="col" style="width: 30%;">Course Description</th>
            <th scope="col" style="width: 30%;">Course Name</th>
          </tr>
        </thead>
        {% for course in user_courses %}
        <tbody>
          <tr>
            <th>{{ course._id }}</th>
            <td>{{ course.description }}</td>
            <td>{{ course.title }}</td>
          </tr>
        </tbody>
        {% endfor %}
    {% else %}
      <p>You have not created to any courses. Click on the new courses tab to upload a course.</p>
    {% endif %}
      </table>
{% endblock %}

app/templates/teacher/upload-course.html
{% extends 'teacher/base-teacher.html' %}
{% block content %}
<section class="holder">
    <div class="container">
        <h2>Create Course</h2>
        <form id="courseForm">
            <div class="form first">
                <div class="details personal">
                    <span class="title">Course Details</span>
                    <div class="fields">
                        <div class="input-field">
                            <label for="course-title">Course Title</label>
                            <input type="text" id="course-title" name="course_title" placeholder="Enter course title" required>
                        </div>
                        <div class="input-field">
                            <label for="course-description">Course Description</label>
                            <textarea id="course-description" name="course_description" placeholder="Enter course description" required></textarea>
                        </div>
                        <div class="input-field">
                            <label for="instructor-id">Instructor ID</label>
                            <input type="text" id="instructor-id" name="instructor_id" placeholder="Enter your Instructor ID" required>
                        </div>
                        <div class="input-field">
                            <label for="modules">Modules</label>
                            <textarea id="modules" name="modules" placeholder="Enter course modules, separated by commas" required></textarea>
                        </div>

                        <div class="input-field">
                            <label for="course-link">Link to The Course</label>
                            <input type="text" id="link" name="course_link" placeholder="Enter link to Course" required>
                        </div>
                    </div>
                    <div class="buttons">
                        <button type="reset" class="backBtn">
                            <i class="uil uil-times-circle"></i>
                            <span class="btnText">Cancel Entry</span>
                        </button>
                        <button type="submit" class="submitBtn" id="submitBtn">
                            <span class="btnText">Submit</span>
                            <i class="uil uil-check-circle"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('courseForm').addEventListener('submit', function(event) {
            event.preventDefault();
            // Gather form data
            const formData = {
                title: document.getElementById('course-title').value,
                description: document.getElementById('course-description').value,
                instructor: document.getElementById('instructor-id').value,
                students_enrolled: [],
                lessons: document.getElementById('modules').value.split(',').map(module => module.trim()),
                embed_link:document.getElementById('link').value
            };

            // Post data as JSON
            fetch("/api/v1/post_courses", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(formData)
            })
            .then(response => response.json())
            .then(data => {
                // Show SweetAlert confirmation message
                Swal.fire({
                    icon: 'success',
                    title: 'Course Submitted!',
                    text: 'Redirecting to Home Page...',
                    showConfirmButton: false,
                    timer: 2000
                })
            })
            .catch(error => {
                console.error('Error:', error);
                Swal.fire({
                    icon: 'error',
                    title: 'Submission Failed',
                    text: 'Please try again later.'
                });
            });
        });
    });
</script>
{% endblock %}

app/templates/teacher/upload.html
{%extends 'base-teacher.html'%}
{% block content %}