app/routes.py
from flask import Blueprint, redirect, url_for, session, render_template, current_app, flash,get_flashed_messages,jsonify
from flask_login import login_user, logout_user, login_required, current_user
from app.models import User, Course
from app.forms import RegistrationForm, LoginForm, Enroll
from app.link_handler import get_src

main = Blueprint('main', __name__)

# Define the routes for the main blueprint
@main.route('/')
def index():
    return render_template('landing.html')


@main.route('/dash')
@login_required
def dashboard():
    name = current_user.name
    user_id = current_user.id
    user_email = current_user.email
    user_marks = User.get_user_marks(user_email)
    # print('this is the user marks', user_marks)
    # print('this is the user email', user_email)
    
    
    course_ids = User.get_user_courses(user_email)
    # print('this is the course ids', course_ids)
    courses = []    
    for course_id in course_ids:
        course = Course.get_course(course_id)
        course['src'] = get_src(course['embed_link'])
        courses.append(course)
    
    courses_marks = []
    if user_marks:
        for mark in user_marks:
            course = Course.get_course(mark['course_id'])
            courses_marks.append({'course': course, 'marks': mark['marks']})
            
    # print('this is courses marks', courses_marks)
    # print('this is course in courses marks', courses_marks[0]['course'])
    
        
        # print('in routes course', course['src'])

    # print(' this is the user email', user_email)
    # print('I should print courses here', courses)

    return render_template('student/dashboard.html', courses=courses, name=name, user_id=user_id, user_email=user_email, courses_marks=courses_marks)

@main.route('/chat')
@login_required
def chatbot():
    return render_template('student/chatbot.html')

@main.route('/learning')
@login_required
def learning():
    return render_template('student/learning.html')

@main.route('/test')
@login_required
def test():
    email = current_user.email
    name = current_user.name
    courses = User.get_user_courses(email) or []
    # course_dict = {}
    # course_dict[f'{name}\'s courses'] = courses or {}
    return render_template('student/test.html', courses=courses, name=name, email=email)

# TODO: Check why it is not validating  
@main.route('/courses', methods=['GET', 'POST'])
def courses(email=None, course_id=None):
    enroll = Enroll()
    if enroll.validate_on_submit():
        email = enroll.email.data
        User.add_course_to_user(email, course_id)
    # print("didnt validate the form") 
    courses = Course.get_all_courses()
    return render_template('student/courses.html', courses=courses, enroll=enroll)

@main.route('/liked_courses')
def liked_courses():
    return render_template('student/liked-course.html')

@main.route('/notification')
def notification():
    return render_template('student/notification.html')


@main.route('/auth', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data
        role = form.role.data
        existing_user = User.get_by_email(email)
        if existing_user is None:
            user = User.create(name, email, password, role)
            login_user(user)
            if role == 'student':
                return redirect(url_for('main.dashboard'))
            elif role == 'teacher':
                return redirect(url_for('main.dashboard_teacher'))
        else:
            flash('A user with that email already exists.')
    login_form = LoginForm()
    flash_messages = get_flashed_messages(with_categories=True)
    return render_template('auth.html', register_form=form, login_form=login_form, flash_messages=flash_messages)


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.get_by_email(form.email.data)
        if user and user.check_password(form.password.data):
            user_json = user.user_to_json()
            print('this is the user json', user_json)          
            login_user(user)
            if user_json['role'] == 'student':
                print('this is the user role', user.role )
                return redirect(url_for('main.dashboard'))
            elif user_json['role'] == 'teacher':
                print('this is the user role', user.role )
                return redirect(url_for('main.dashboard_teacher'))
            elif user_json['role'] == None:
                flash('Please Sign up')
            print('after all the checks')
        else:
            flash('Invalid email or password.')
    register_form = RegistrationForm()
    flash_messages = get_flashed_messages(with_categories=True)
    return render_template('auth.html', register_form=register_form, login_form=form, flash_messages=flash_messages)
    # return render_template('login.html', register_form=register_form, login_form=form)

# Google login
@main.route('/login-google')
def login_google():
    google = current_app.config['oauth_google']
    redirect_uri = url_for('main.authorize', _external=True)
    return google.authorize_redirect(redirect_uri)

@main.route('/auth/callback')
def authorize():
    google = current_app.config['oauth_google']
    token = google.authorize_access_token()
    userinfo = google.parse_id_token(token)
    user = User.get(userinfo['sub'])
    if not user:
        user = User.create(userinfo['sub'], userinfo['name'], userinfo['email'])
    session['user'] = {'id': userinfo['sub'], 'name': userinfo['name'], 'email': userinfo['email']}
    login_user(user)
    return redirect(url_for('main.dashboard'))

@main.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('user', None)
    return redirect(url_for('main.index'))

# teachers routes
####

#
######
#
#
#
#
#
#
#
#######

@main.route('/dashboard-teacher')
@login_required
def dashboard_teacher():
    all_students = User.get_all_users()
    my_courses = User.get_user_courses(current_user.email)

    course_names = []
    for course in my_courses:
        course = Course.get_course(course)
        course_names.append(course)
        
        
    my_students = []
    for student in all_students:
        if student['role'] == 'student':
            for course in student['courses']:
                if course in my_courses:
                    my_students.append(student)
                    break
    
    print('COURSE NAMES', course_names)

    return render_template('teacher/dashboard-teacher.html', my_students=my_students, course_names=course_names)


@main.route('/students')
def students():
    users = User.get_all_users()
    for user in users:
        if user['email'] == current_user.email:
            user_info = user
        user_courses = user_info['courses']
        courses = []
        for course in user_courses:
            course = Course.get_course(course)
            courses.append(course)
        print('this is the courses', courses)
    return render_template('teacher/students.html',user_courses=courses)

@main.route('/add-courses')
def add_courses():
    
    return render_template('teacher/upload-course.html')

@main.route('/send-notification')
def notify():
    return render_template('teacher/send-notification.html')


##
#
#
###
@main.route('/settings')
def settings():
    current_user = User.get(session['_user_id'])
    print('this is the current user', current_user)
    user_json = current_user.user_to_json()
    role = current_user.marks # the simple fix...
    return render_template('settings.html', role=role)

 

app/templates/auth.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <title>Login | Academie Franco</title>
</head>

<body>
    {% if flash_messages %}
        <div id="flash">
            <div class="flash-messages">
                {% for category, message in flash_messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <div class="container" id="container">
        <div class="form-container sign-up">
            <form method="POST" action="{{ url_for('main.register') }}">
                {{ register_form.hidden_tag() }}
                <h1>Create Account</h1>
                <div class="social-icons">
                    <a href="#" class="icon"><i class="fa-brands fa-google-plus-g"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-facebook-f"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-github"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-linkedin-in"></i></a>
                </div>
                <span>Use your email to register</span><br>
            <div>    
                {{ register_form.role.label }}<br>
                {{ register_form.role() }}<br>
                {% for error in register_form.role.errors %}
                <span style="color: red;">{{ error }}</span><br>
                {% endfor %}
                {{ register_form.name.label }}<br>
                {{ register_form.name(size=32) }}<br>
                {% for error in register_form.name.errors %}
                <span style="color: red;">{{ error }}</span><br>
                {% endfor %}
                {{ register_form.email.label }}<br>
                {{ register_form.email(size=32) }}<br>
                {% for error in register_form.email.errors %}
                <span style="color: red;">{{ error }}</span><br>
                {% endfor %}
                {{ register_form.password.label }}<br>
                {{ register_form.password(size=32) }}<br>
                {% for error in register_form.password.errors %}
                <span style="color: red;">{{ error }}</span><br>
                {% endfor %}
                {{ register_form.confirm_password.label }}<br>
                {{ register_form.confirm_password(size=32) }}<br>
                {% for error in register_form.confirm_password.errors %}
                <span style="color: red;">{{ error }}</span><br>
                {% endfor %}
            </div>
                <button type="submit">Register</button>
            </form>
        </div>
        {% if flash_messages %}
                <div class="flash-messages">
                    {% for category, message in flash_messages %}
                    <div class="flash-message alert alert-{{ category }}">
                        {{ message }}
                    </div>
                    {% endfor %}
                </div>
        {% endif %}
        <div class="form-container sign-in">
                <form method="POST" action="{{ url_for('main.login') }}">
                    {{ login_form.hidden_tag() }}
                    <h1>Sign In</h1>
                    <div class="social-icons">
                        <a href="{{ url_for('main.login_google') }}" class="icon"><i class="fa-brands fa-google-plus-g"></i></a>
                        <a href="#" class="icon"><i class="fa-brands fa-facebook-f"></i></a>
                        <a href="#" class="icon"><i class="fa-brands fa-github"></i></a>
                        <a href="#" class="icon"><i class="fa-brands fa-linkedin-in"></i></a>
                    </div>
                    <span>Use your email</span><br>
                    <div>
                    {{ login_form.email.label }}<br>
                    {{ login_form.email(size=32) }}<br>
                    {% for error in login_form.email.errors %}
                    <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                    {{ login_form.password.label }}<br>
                    {{ login_form.password(size=32) }}<br>
                    {% for error in login_form.password.errors %}
                    <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                    </div>
                    <a href="#">Forgot your password?</a><br>
                    <button type="submit">Sign In</button>
                </form>
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-left">
                    <h1>Welcome</h1>
                    <img src="https://scontent-bog1-1.xx.fbcdn.net/v/t39.30808-6/305935996_445997794220603_2697507958715874722_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=5f2048&_nc_ohc=NFgouFl4v6QAX-bixKX&_nc_ht=scontent-bog1-1.xx&oh=00_AfAjH_1853v7nu_M7kbiSTXx-p8XVUKcPEqipGJQCjm9hg&oe=654F3F02" alt="" class="logo" width="150px">
                    <p>Register with your personal details</p>
                    <button class="hidden" id="login">Sign In</button>
                </div>
                <div class="toggle-panel toggle-right">
                    <h1>Welcome!!</h1>
                    <img src="https://scontent-bog1-1.xx.fbcdn.net/v/t39.30808-6/305935996_445997794220603_2697507958715874722_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=5f2048&_nc_ohc=NFgouFl4v6QAX-bixKX&_nc_ht=scontent-bog1-1.xx&oh=00_AfAjH_1853v7nu_M7kbiSTXx-p8XVUKcPEqipGJQCjm9hg&oe=654F3F02" alt="" class="logo" width="150px">
                    <p>Enter your personal details</p>
                    <button class="hidden" id="register">Register</button>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/login.js') }}"></script>
</body>

</html>

app/templates/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Academie Franco | Settings</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/settings.css') }}">

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <!-- Sidebar -->
      <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block sidebar">
        <h5 class="nav-header">Settings</h5>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#" onclick="window.history.back()">
              <i class="fa fa-tachometer-alt"></i>
              Back Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.logout') }}">
              <i class="fa fa-sign-out-alt"></i>
              Logout
            </a>
          </li>
        </ul>
      </nav>
      <!-- Main content -->
      <main class="col-md-9 ms-sm-auto col-lg-10 main-content">
        <div class="profile-header">
          <img src="https://via.placeholder.com/120" alt="Avatar" class="avatar">
          <h1 class="name">{{ current_user.name }}</h1>
          <p class="bio"></p>
        </div>

        <div class="info-section mt-4">
          <h2 class="mb-4">Profile Information</h2>
          <div class="info-item">
            <div class="info-label">Full Name:</div>
            <div class="info-value">{{ current_user.name }}</div>
            <div class="edit-btn" data-bs-toggle="modal" data-bs-target="#editModal" data-field="firstName">Edit</div>
          </div>
          <div class="info-item">
            <div class="info-label">Email:</div>
            <div class="info-value">{{ current_user.email }}</div>
            <div class="edit-btn" data-bs-toggle="modal" data-bs-target="#editModal" data-field="email">Edit</div>
          </div>
          <div class="info-item">
            <div class="info-label">Role:</div>
            <div class="info-value">{{ role }}</div>
          </div>
        </div>
      </main>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gtomfOczgL5g5O99zx4xAb5kc4evY7xU4T8Fj6FvMz5AbW81j" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-6p5LxJ9tV+v/aEF3y7h6D4FVtA76eJ8U1qR+IH09swhH6U19XEp+eC3zyL2W4Al9" crossorigin="anonymous"></script>
  <script>
  </script>
</body>
</html>